### ISSUE TITLE
Cannot use back button after trying to add a node on settings

### ISSUE THREAD

**Issue by gcarreno** [Stevengez/NosoWallet-Android#1]
Hey @Stevengez,

As I told you on Discord, if I try to add a node on the list by:
1. Press Settings
2. Press +
3. Press Back

Nothing happens.

I can back up with the system :arrow_backward: but if I press on the settings, the add dialog is still open and can't back out of it.

Cheers,
Gus

**Comment by Stevengez** [comment]
With that explanation I understood the issue better haha
I'll have it fixed in the next update, thanks for the report

**Comment by Stevengez** [comment]
I got it fixed in the last release
